# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mongo:5
    restart: always
    ports:
      # <Port exposed>:< MySQL Port running inside the container>
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      # <file_system_path>:<container_path>
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      # ME_CONFIG_MONGODB_URL: mongodb://root:admin@db:27017/
      ME_CONFIG_MONGODB_URL: mongodb://db:27017/nest-pokemon
      ME_CONFIG_BASICAUTH: false
